# Generated by Django 4.2.10 on 2024-02-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroceryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grocery_store", models.CharField(max_length=100)),
                ("date_start", models.DateField()),
                ("date_end", models.DateField()),
                ("quantity", models.IntegerField()),
                ("price_per_unit", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
