# Generated by Django 4.2.10 on 2024-02-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_checker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroceryStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, upload_to="images/")),
            ],
        ),
        migrations.RemoveField(
            model_name="groceryitem",
            name="grocery_store",
        ),
        migrations.AddField(
            model_name="groceryitem",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
