# Generated by Django 4.2.10 on 2024-02-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "price_checker",
            "0002_grocerystore_remove_groceryitem_grocery_store_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="groceryitem",
            name="grocery_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="price_checker.grocerystore",
            ),
        ),
    ]
